### ISSUE TITLE
Bug: multiple diagnostic rules in one line

### ISSUE THREAD

**Issue by chrisgrieser** [amaanq/tree-sitter-luadoc#1]
First, thanks for this parser, just discovered it by chance yesterday, and it makes annotations much nicer 😊 

A minor bug: with multiple diagnostic rules in one line, only the first one gets highlighted
![image](https://user-images.githubusercontent.com/73286100/227503425-6bc76a40-e2a9-4d89-97a8-9d9d7902231e.png)

**Comment by amaanq** [comment]
Thanks for the report! I will fix this and add a couple missing annotations shortly then :)

**Comment by amaanq** [comment]
Fixed, nvim-ts will be updated soon
