### ISSUE TITLE
type name does not allow `.`

### ISSUE THREAD

**Issue by tmillr** [amaanq/tree-sitter-luadoc#3]
I'm not sure if this is an issue with a query or this grammar, but it seems that `.` characters within type names are not handled correctly, leading to incorrect/missing highlighting. Using a `.` like this is a common way to namespace types under a unique name (e.g. the name of the package where the type is defined).

For example (please ignore the red squiglies):

<img width="422" alt="Screenshot 2023-05-18 at 2 36 29 AM" src="https://github.com/amaanq/tree-sitter-luadoc/assets/45028928/274bdec6-d26a-46e1-900d-52eb09407ed1">

This issue appears to exist basically wherever a type name is accepted (e.g. `@alias`, `@type`, etc.).

**Comment by tmillr** [comment]
@amaanq

**Comment by amaanq** [comment]
Sorry - I was on the verge of leaving for vacation when you posted this, and I missed this when I got back, will fix now

**Comment by amaanq** [comment]
Closed since e819114

**Comment by tmillr** [comment]
Awesome thank you!
