### ISSUE TITLE
Need more annotations

### ISSUE THREAD

**Issue by wookayin** [amaanq/tree-sitter-luadoc#9]
Annotations that are not recognized as of 990926b13488a4bc0fc0804fc0f8400b5b0a1fb4 or v1.0.1:

- `@link`
- `@since`
- `@as` (e.g. `--[[@as some.type]]`); see also #8 Problem 6

Those are not documented in https://emmylua.github.io/annotation.html but used in many places in neovim's core runtime lua files. Example: https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/protocol.lua

Q: If an user write a custom query file like
```
[
  "@since"
] @keyword
```
this will result in invalid query error as `@since`, etc. are not defined in the grammar. It's quite inconvenient that one needs to write a grammar and update the parser in order to match "string literals". Is there any easy way to do so?

**Comment by amaanq** [comment]
thanks and sorry for the long response time, they're added now

There's no easy way to use literal nodes in a query if it's not in the grammar, it has to be in the grammar.

**Comment by wookayin** [comment]
Awesome! I will try out the latest master, thanks.

**Comment by amaanq** [comment]
I overwrote it, sorry! try 6ebdac83b4789069c4939713efae7176cc3126de

**Comment by wookayin** [comment]
Thanks, for the record (sorry to say this so late but..): 

- Later I recognized that `{@link ...}` and `@since` is NOT a standard LuaCATS annotation, so probably we should not support this officially. This is more in concern for neovim/plugin devs, and in retrospect way too niche/specific for this LSP meta protocol file (Actually this is not a really intended use) There are also many other non-standard LuaCATS annotations used in neovim, but I don't think this deserves tree-sitter parser updates.

- `[[ @as .. ]]` `(as_annotataion)` looks great though.

**Comment by amaanq** [comment]
Hm, I'm okay to keep them in, I don't think it hurts and it might prompt lua ls to support them later, but if you think the parser is better off without it then I can remove it :slightly_smiling_face:

**Comment by wookayin** [comment]
Thanks! I will debate myself a bit more, but a quick ping/heads-up before tagging 'release' would be appreciated just in case I forget about it.

Maybe we could have a more general rule for all other unrecognized annotations `@{name} [desc]` (rather than ERROR) which can supersede all these non-standard annotations.
